version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: app-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d/migrations
      - ./migrate.sh:/docker-entrypoint-initdb.d/00-migrate.sh
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: 